[BLD-39308] - added requested permissions for targeting sdk 29+
bold360ai/bold360-mobile-samples-android pull request #25
Opened 2020-10-29 08:35 UTC by ozLogmein

2020-10-29 17:01 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomFileUpload.kt
> +        permissions.forEach {
i think this can be done with map 
permissions.map{ActivityCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED)}
than filter the ones that are true - but u need to check if the generated java code is better or same
just for practice - this can be nice

2020-10-29 17:04 UTC, tehilaR2 requested changes

2020-10-29 17:04 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomFileUpload.kt
>                  if (grantResults.isNotEmpty() && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
if you're asking for multiple permissions and only the first was granted? - you need to know how many permissions you requested and got permission to.

2020-10-29 19:41 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomFileUpload.kt
> +        permissions.forEach {
so after a check.
my solution's bitcode is shorter.
The filtering is a lot of code ! that was a good lesson.

2020-11-02 12:36 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomFileUpload.kt
> +                    Log.w(TAG, "Not granted permissions:  $notGranted")
add a toast message for the user to see this message

2020-11-02 12:36 UTC, tehilaR2 approved these changes
please flow the single comment i added

2020-11-02 12:45 UTC, merged