Bld 42482
bold360ai/bold360-mobile-samples-android pull request #28
Opened 2020-12-30 09:53 UTC by ozLogmein

2021-01-05 13:30 UTC, tehilaR2 reviewed
General:
1. Why i can select last chat on the full demo if none exists.
2. "Continue last" without restore - not working
3. if i start bold chat after a bot chat, i see the prev chat history
4. i got an error message "the account is not restorable" and nothing happens. second press on the start chat takes me to the prechat. WHT - ??
back on that prechat takes me to the chat screen with the bot chat history (u need to keep history for each account - see the history in the samples)
5. async sample has the restore switch twice and i get "account is not restorable" every time i want to start the chat
6. from the samples the async chat starts as it should 
but we get unavailable which should be checked

2021-01-07 15:04 UTC, tehilaR2 requested changes
I think you should recheck if we reached our goals regarding, giving the customer a simple and clear reference, on how to activate and handle features we display on the samples.
I'm not sure if the usage of the ChatProvider and other like it, will not confuse the user and make the code less readable.
we can have handlers to ease and separate code from the activity, but it should be divided to small controllers classes - per subject (exp: if the sample support history activity adds the history handler... i know that u add the history repository, but you can wrap this with a clear purpose method: addHistorySupport() -> inside you do what you're doing now)

This is only my opinion .. think about it, go to a sample and see if its clear what you should do.

2021-01-12 10:30 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/MainActivity.kt
> +    private lateinit var singletonSamplesViewModelFactory: SingletonSamplesViewModelFactory
deleted

2021-01-12 10:30 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/loginForms/AccountFormController.kt
> +    private val getFragmentManager: () -> FragmentManager? = { wFragmentManager.get() }
the activity who passed it

2021-01-12 10:33 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/FullDemoSample.kt
> +    private fun openFilePicker() {
changed

2021-01-12 10:34 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/FullDemoSample.kt
> +    inner class CustomFormProvider : FormProvider {
removed

2021-01-12 10:38 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/loginForms/SharedDataHandlers.kt
> +    fun onSubmit(account: Account)
removed from the interface

2021-01-12 10:46 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/BoldUploadNoUI.kt
> +        setSupportActionBar(findViewById(R.id.sample_toolbar))
I know, its not working otherwise since the contentView is different for each activity, and the Samples activity doesn't render a contantView since its abstract.

2021-02-09 19:27 UTC, closed without merging

2021-02-09 19:27 UTC, ozLogmein commented
refactor needed