Samples demo refactor
bold360ai/bold360-mobile-samples-android pull request #30
Opened 2021-02-09 19:38 UTC by ozLogmein

2021-02-10 12:25 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/MainActivity.kt
> +        ).let { topics ->
why this let block is needed

2021-02-10 12:33 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    private var accountData: JsonObject = JsonObject()
isn't this part of the data that should be hold on the ViewModel?

2021-02-10 12:39 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    private val formFieldsData: JsonArray
why this is needed as a property?

2021-02-10 12:41 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    open var extraDataFields: (() -> List<FormFieldFactory.FormField>) = { listOf() }
why is that needed as a property?
the form should be created when needed. The factory should know what are the needed fields for each chat

2021-02-10 12:45 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    abstract fun startChat(savedInstanceState: Bundle? = null)
this is not common for all samples

2021-02-10 13:12 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    private var accountData: JsonObject = JsonObject()
removed

2021-02-10 13:17 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        val loginFormViewModel: LoginFormViewModel by viewModels()
u don't login to anything, its confusing (already talked about it)

2021-02-10 13:23 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        accountController = AccountController(containerId, supportFragmentManager.weakRef(), JsonSharedDataHandler())
i don't see why this class is needed, also why u need the AccountPresenter 
They take the container and add the fragment to it.
If u want to prevent code duplication of this operation, consider an extension method that will do that.

2021-02-10 13:23 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        presentForms()
which forms are there?

2021-02-10 13:27 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +            supportFragmentManager
this can become an extension method or a method that closes the account form, we may need it elsewhere

2021-02-10 13:30 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    open var extraDataFields: (() -> List<FormFieldFactory.FormField>) = { listOf() }
ok

2021-02-10 13:30 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    private val formFieldsData: JsonArray
ok

2021-02-10 13:31 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    abstract fun startChat(savedInstanceState: Bundle? = null)
ok

2021-02-10 13:32 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        val loginFormViewModel: LoginFormViewModel by viewModels()
ok

2021-02-10 13:34 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        accountController = AccountController(containerId, supportFragmentManager.weakRef(), JsonSharedDataHandler())
lets talk about this one

2021-02-10 13:35 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/BasicChat.kt
> +        return "some PGP encrypted key string [${SystemUtil.generateTimestamp()}]"
this is specific for bold live chat, why is it here?

2021-02-10 13:36 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        presentForms()
restoration and account
changed the method name

2021-02-10 13:39 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +            supportFragmentManager
lets talk about this one

2021-02-10 13:41 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/BasicChat.kt
> +        return "some PGP encrypted key string [${SystemUtil.generateTimestamp()}]"
needed at the Restoration (After chat selection) and at the BoldChat 
The Restoration inherit from the Basic, not from Bold.
And the Bold also inherits from the Basic.

2021-02-10 13:41 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +                        formFields?.addView(AppCompatTextView(context).apply {
why not using a factory for that

2021-02-11 11:04 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/history/RoomHistoryProvider.kt
> -    fun clearAll() {
why was it removed?
we had clear for specific account, and clear of all chats.
now if i want to clear all, i need to verify that the targetId is null

2021-02-11 11:05 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/BasicChat.kt
> +    protected fun hasChatController(): Boolean { return ::chatController.isInitialized && chatController.hasOpenChats() }
add a fixme comment on this one to be changed once will have a new SDK version with the `chatController.wasDestructed` fix

2021-02-11 11:22 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/MainActivity.kt
> +        ).let { topics ->
instead of creating a property

2021-02-11 11:27 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/history/RoomHistoryProvider.kt
> -    fun clearAll() {
that's the clear method handles it:

`override fun clear() {

        coroutineScope.launch(Dispatchers.IO) {
            targetId?.run {
                historyDao.delete(this)
            } ?: HistoryRoomDB.getInstance(context).clearAllTables()
        }
    }`

2021-02-11 11:46 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        sampleFormViewModel.updateFormData(extraDataFields?.invoke())
is this method updates the fields values?

2021-02-11 11:48 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        sampleFormViewModel.sampleData.observe(this, Observer<LoginData> {
set the observer before the present form action

2021-02-11 11:49 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        sampleFormViewModel.updateFormData(extraDataFields?.invoke())
changed to 'createForm'

2021-02-11 11:49 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    private val sampleRepository: SampleRepository = JsonSampleRepository()
set this from outside, inject the repository don't define it here

2021-02-11 11:51 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    private var accountData: JsonObject = JsonObject()
if we used some other repository, like Room DB, were u still having this member?

2021-02-11 11:51 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    val sampleData: LiveData<LoginData> = _sampleData
`LoginData` -> `SampleData`

2021-02-11 11:52 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        return sampleRepository.isRestorable(app.applicationContext, chatType.value ?: ChatType.None)
why do u need the application context here?

2021-02-11 11:53 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +class SampleFormViewModel(private val app: Application) : AndroidViewModel(app) {
why r u referencing the application?

2021-02-11 11:56 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +class SampleFormViewModel(private val app: Application) : AndroidViewModel(app) {
why r u saving the application as a member here. It is accessible via the base class

2021-02-11 12:03 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        _chatType.value = chatType
since when we have variables names with "_", this is not flutter

2021-02-11 12:08 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        _formData.value = FormDataFactory.createForm(_chatType.value ?: ChatType.None, extraFields).applyValues( getSavedAccount() )
`createFrom` is confusing since it suggests that u're actually create the form. 
it should mean create the forn fields

2021-02-11 12:26 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    val sampleData: LiveData<LoginData> = _sampleData
why do u need this second member?
u can declare the field as readonly access

2021-02-11 12:27 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    fun onAccountData() {
i don't understand this method 
u have livedata member which consist of 2 other members? why??

2021-02-11 12:29 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +                it.asJsonObject.takeIf { formField -> formField.getString(FieldProps.FormType) == formType }?.let { formField ->
why this check is needed, why is there an option that u'll get a field that is not of the current chat type?

2021-02-11 12:34 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +                            (this as? ContextBlock)?.apply { initContextBlock(view?.findViewById(R.id.scroller)) }
why this is here?
if the field is a context field the creation of it should be done by the factory.
The context "block" with all the views init should be created by the factory and added to the view as other views.
U can create the layout that holds it inside the factory

2021-02-11 12:35 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +        sampleFormViewModel.sampleData.observe(this, Observer<LoginData> {
ok

2021-02-11 12:35 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    private val sampleRepository: SampleRepository = JsonSampleRepository()
ok

2021-02-11 12:36 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +        FieldViewFactory.clear()
what r u clearing

2021-02-11 12:37 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    private var accountData: JsonObject = JsonObject()
yes. we don't need to go tho the repo for each call to the accountData

2021-02-11 12:38 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    val sampleData: LiveData<LoginData> = _sampleData
thanks

2021-02-11 12:41 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        return sampleRepository.isRestorable(app.applicationContext, chatType.value ?: ChatType.None)
ok, used weak

2021-02-11 12:45 UTC, tehilaR2 requested changes
see comments

2021-02-11 12:52 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +class SampleFormViewModel(private val app: Application) : AndroidViewModel(app) {
Slack

2021-02-11 12:54 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        _chatType.value = chatType
its by android codlab : 

https://developer.android.com/codelabs/advanced-android-kotlin-training-notifications#2

https://github.com/googlecodelabs/android-kotlin-notifications/blob/master/app/src/main/java/com/example/android/eggtimernotifications/ui/EggTimerViewModel.kt

2021-02-11 12:56 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +        _formData.value = FormDataFactory.createForm(_chatType.value ?: ChatType.None, extraFields).applyValues( getSavedAccount() )
ok

2021-02-11 13:03 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleFormViewModel.kt
> +    fun onAccountData() {
At the chat form we use;
                    sampleFormViewModel.addAccountProperty(key, value)
on all the form fields.
then when all is done, we call this method and observe the final accountData (through the sampleData)

Another way would be to save a temporary jsonArray, apply it to the AccountData object and observe it instead.
But, then, the AccountData would be public - I think it should be private (the samples cannot change it directly)

2021-02-11 13:04 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +                it.asJsonObject.takeIf { formField -> formField.getString(FieldProps.FormType) == formType }?.let { formField ->
As I wrote on slack yesterday:
' A point that i want to consult with you on:
formType - i dont like to define the form type, but i hadn’t found a better way to do this because:
      a. I dont want to use alot of ifs !
      b. I want the sample to be able to add fields to a specific form (Account/Restoration) dynamically, so the field needs to have this kind of info
So i added formType to the formData (JsonArray). and to the fields (FormField)
Specific fields (such as the ContextBlock) uses known form type.
If you have another way please let me know. '

2021-02-11 13:07 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +        FieldViewFactory.clear()
the radio group

2021-02-11 13:08 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +                            (this as? ContextBlock)?.apply { initContextBlock(view?.findViewById(R.id.scroller)) }
the factory doesn't know the scroller.
the scroller is the parent of the formFields

2021-02-17 16:33 UTC, tehilaR2 requested changes
Good job

2021-02-17 16:33 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/defs/FieldType.java
> +    String Options = "radioGroup";
u didn't include the Options and Option in the StringDef array, and u're accessing it in the code

2021-02-17 16:33 UTC, tehilaR2 commented on SDKSamples/common/src/main/res/layout/form_fields_view.xml
> +</com.common.utils.chatForm.FormFieldsContainer>
not in use, u're creating the LinearLayout dynamically

2021-02-17 16:33 UTC, tehilaR2 commented on SDKSamples/fulldemo/src/androidTest/java/com/sdk/fulldemo/ExampleInstrumentedTest.kt
> +import org.junit.Assert.*
u didn't set the imports on your nAndroid Studio to prevent wildcards imports.
this won't go through ktlint if we'll use it which standardized code according to kotlin guidelines

2021-02-17 16:33 UTC, tehilaR2 commented on SDKSamples/fulldemo/src/main/java/com/sdk/fulldemo/FullDemo.kt
> +        super.extraDataFields?.invoke()!!.toMutableList().apply {
why do u need to use `!!` here.
why not checking if not null, do u want it to crash in case of null?

2021-02-17 17:14 UTC, tehilaR2 requested changes

2021-02-17 17:14 UTC, tehilaR2 commented on SDKSamples/app/build.gradle
>  }
since u import the `common` repo there might be some duplicated imports, try to check what u already get by importing common and remove what is not needed.

2021-02-17 17:14 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/NotificationsReceiver.kt
> +package com.common.chatComponents
why u moved it to common?

2021-02-17 17:14 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/handover/CustomHandoverHandler.kt
> +    private val handler = Handler(Looper.myLooper()!!)
mamash lo!
Looper.myLooper()?.let{ 
Lopper.prepare() 
Looper.myLooper()
}

2021-02-17 17:14 UTC, tehilaR2 commented on SDKSamples/fulldemo/.gitignore
> +/build
should not be included in source control

2021-02-17 17:14 UTC, tehilaR2 commented on SDKSamples/fulldemo/build.gradle
> +}
please check which of the dependencies can be removed due to the common module import

2021-02-17 18:26 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/PrechatExtraData.kt
> +            FormFieldFactory.TextInputField(ChatType.Bot, DataKeys.LastName, "", "Last Name", false),
we can, I changed it

2021-02-17 19:08 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/ChatAvailability.kt
> -class CheckAvailability : AppCompatActivity() {
We don't need it,,
It checked availability and then opened the BoldChat, we have BoldChatAvailability for that.

2021-02-17 19:10 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomUIChat.kt
> +        findViewById<TextView>(R.id.topic_title).text = intent.getStringExtra("title")
Because, this field is at activity_basic and it is at another module - its a known issue

2021-02-18 09:48 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/NotificationsReceiver.kt
> +package com.common.chatComponents
to be used by the samples if would be needed at the feature

2021-02-18 09:50 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/handover/CustomHandoverHandler.kt
> +    private val handler = Handler(Looper.myLooper()!!)
It was before... long time ago

2021-02-18 09:54 UTC, ozLogmein commented on SDKSamples/fulldemo/.gitignore
> +/build
removed this file

2021-02-21 07:24 UTC, ozLogmein commented
> r u using this file at all?

2021-02-21 13:51 UTC, ozLogmein commented on SDKSamples/fulldemo/src/androidTest/java/com/sdk/fulldemo/ExampleInstrumentedTest.kt
> +import org.junit.Assert.*
I don't understand, lets talk

2021-02-22 11:39 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/MainActivity.kt
> +//                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
clean up code

2021-02-22 13:25 UTC, tehilaR2 approved these changes

2021-02-22 13:34 UTC, merged