Bld 45005
bold360ai/bold360-mobile-samples-android pull request #31
Opened 2021-03-09 15:31 UTC by ozLogmein

2021-03-15 09:35 UTC, tehilaR2 commented
!! source target should not be master. Every change - feature/bug should start from develop.

2021-03-15 10:17 UTC, tehilaR2 requested changes
This branch should have been started from develop, and should target develop.

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +    private lateinit var binding: AutocompleteActivityBinding
all activities (except MainActivity) are subclasses of SampleActivity, there is no point of recreating the binding member for each one. 
Please check the following: 
[ViewBinding and class hierarchy](https://stackoverflow.com/questions/63686289/how-to-use-abstraction-with-viewbinding-with-base-activity)

(ViewModel as generic is not needed for our use)

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        binding = DataBindingUtil.setContentView(
can this be done in the base class?

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        binding.topicTitle.text = topicTitle
can this be done in the base class?

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +        binding.demoLocalBubbleMessageTextview.text = text
why the view name is so long -> make the id shorter on the XML of this to be shorter as well

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ContextBlock.kt
> +            findViewById<Button>(R.id.add_context).setOnClickListener {
why that can't be accessed by the binding

2021-03-15 10:17 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +        formFieldsContainer = view.findViewById(R.id.formFieldsContainer)
why that can't be accessed by the binding

2021-03-16 12:41 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        binding = DataBindingUtil.setContentView(
yes

2021-03-16 12:41 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +    private lateinit var binding: AutocompleteActivityBinding
yes

2021-03-16 12:42 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        binding.topicTitle.text = topicTitle
yes

2021-03-16 12:43 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +        binding.demoLocalBubbleMessageTextview.text = text
ok

2021-03-16 12:43 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ContextBlock.kt
> +            findViewById<Button>(R.id.add_context).setOnClickListener {
It can, but we don't need binding for 1 view.... its overhead. its better to look for that 1 view

2021-03-16 12:44 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/ChatForm.kt
> +        formFieldsContainer = view.findViewById(R.id.formFieldsContainer)
It can, but we don't need binding for 1 view.... its overhead. its better to look for that 1 view

2021-03-17 16:59 UTC, tehilaR2 requested changes

2021-03-17 16:59 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    lateinit var binding: Binding
why not using by lazy ?

2021-03-17 16:59 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/CustomFormProvider.kt
> +class CustomFormProvider(sampleActivity: AppCompatActivity) : FormProvider {
why was it changed. and now you're doing the casting to get the container.
If it's only works with sample activities, why changing

2021-03-18 08:11 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/SampleActivity.kt
> +    lateinit var binding: Binding
ok

2021-03-18 08:12 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/CustomFormProvider.kt
> +class CustomFormProvider(sampleActivity: AppCompatActivity) : FormProvider {
ok

2021-03-18 09:38 UTC, tehilaR2 approved these changes

2021-03-18 09:52 UTC, merged