[BLD-46898] - added article config to the samples
bold360ai/bold360-mobile-samples-android pull request #33
Opened 2021-06-24 14:06 UTC by ozLogmein

2021-06-27 13:38 UTC, tehilaR2 requested changes

2021-06-27 13:38 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                    margin = intArrayOf(2.px,8.px,2.px,8.px)
if you're using the same px value, the value of activating the 2.px or 8.px should be kept in a variable and be used where needed - since by doing 8.px you're actually activating the retrieval of system service to get the display metrics and you're calculating the same value again and again.

2021-06-27 13:38 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                verticalMargin = Pair(40.px, 0)
can also be `40.px to 0`

2021-06-27 13:38 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomUIChat.kt
> +            text = customUIOption
why the buttons texts are hardcoded on the code and are not using the resources.
BTW:
enum like values can also be configured on resources.

2021-06-28 16:13 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomUIChat.kt
> +                    putExtra("type", customUIOption.toString())
`customUIOption.toString()` Can be replaced with `customUIOption.name`

2021-06-28 16:14 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                intent?.getStringExtra("type") ?: ConfigOption.OVERRIDE.toString()
`ConfigOption.OVERRIDE.toString()` Can be replaced with `ConfigOption.OVERRIDE.name`

2021-06-28 16:28 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomUIChat.kt
> +                    putExtra("type", customUIOption.toString())
customUIOption.name

2021-06-28 16:30 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                intent?.getStringExtra("type") ?: ConfigOption.OVERRIDE.toString()
ConfigOption.OVERRIDE.name

2021-06-28 16:31 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                ConfigOption.ARTICLE_CONFIG.toString() -> configureArticle(context)
ConfigOption. ARTICLE_CONFIG.name

2021-06-29 07:06 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                verticalMargin = Pair(40.px, 0)
V

2021-06-29 07:08 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomUIChat.kt
> +                    putExtra("type", customUIOption.toString())
V

2021-06-29 07:08 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                intent?.getStringExtra("type") ?: ConfigOption.OVERRIDE.toString()
V

2021-06-29 07:08 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/CustomizedUI.kt
> +                ConfigOption.ARTICLE_CONFIG.toString() -> configureArticle(context)
V

2021-06-29 15:49 UTC, tehilaR2 approved these changes

2021-06-30 10:54 UTC, Sapirpardo approved these changes

2021-06-30 11:31 UTC, merged