Bld 46898
bold360ai/bold360-mobile-samples-android pull request #35
Opened 2021-07-01 12:01 UTC by ozLogmein

2021-07-05 10:57 UTC, tehilaR2 requested changes

2021-07-05 10:57 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        var html = "<html><Style>${ArticleFragment.STYLE_TO_HANDLE_TABLES}</Style><body>${article.content}</body></html>"
why was it changed?

2021-07-05 10:57 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        toast(this, error.toString(), background = ColorDrawable(Color.RED))
why not adding an extension method to the samples base activity that will also check if the activity is not on finishing state, to prevent leeks and exceptions

2021-07-05 11:37 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        var html = "<html><Style>${ArticleFragment.STYLE_TO_HANDLE_TABLES}</Style><body>${article.content}</body></html>"
because we changed it at the SDK - the Style tags are not part of the css

2021-07-05 15:29 UTC, tehilaR2 requested changes

2021-07-05 15:29 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        var html = "<html><Style>${ArticleFragment.STYLE_TO_HANDLE_TABLES}</Style><body>${article.content}</body></html>"
i was talking about the content part:
was `${article.content ?: "Not Available"}`
now `${article.content}`

("Not available" should be taken from resources)

2021-07-05 15:29 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/BoldUploadNoUI.kt
> +            toast("Chat unavailable", background = ColorDrawable(Color.GRAY))
string from resources
same for other strings

2021-07-05 15:29 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/Utils.kt
> +        com.nanorep.sdkcore.utils.toast(this, text, timeout, background)
why do u need the whole path can't it be imported

2021-07-05 15:29 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/History.kt
> +        enableMenu(historyMenu, true)
this won't make the history menu visible, only enabled.

2021-07-05 16:52 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        var html = "<html><Style>${ArticleFragment.STYLE_TO_HANDLE_TABLES}</Style><body>${article.content}</body></html>"
Because article.content is non-null now

2021-07-05 16:52 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/Autocomplete.kt
> +        toast(this, error.toString(), background = ColorDrawable(Color.RED))
did

2021-07-05 17:49 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/utils/Utils.kt
> +        com.nanorep.sdkcore.utils.toast(this, text, timeout, background)
because I decided to call the extension method by the same name.

2021-07-05 17:51 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/History.kt
> +        enableMenu(historyMenu, true)
doesn't  the enableMenu method do that?:
` protected fun enableMenu(@Nullable menuItem: MenuItem?, enable: Boolean) {
        if (menuItem != null) {
            menuItem.isEnabled = enable
            if (enable && !menuItem.isVisible) menuItem.isVisible = true
        }
    }`

2021-07-06 09:03 UTC, tehilaR2 approved these changes
make sure to pull branch changes before merge!

2021-07-06 13:51 UTC, tehilaR2 requested changes

2021-07-06 13:51 UTC, tehilaR2 commented on SDKSamples/common/src/main/res/menu/menu_main.xml
> -        android:title="@string/end_current_chat"
why did u change that?
i changed it so we won't have conflict with the chat_end string of the live chat button

2021-07-06 13:51 UTC, tehilaR2 commented on SDKSamples/common/src/main/res/values/strings.xml
> -    <string name="end_current_chat">End current chat</string>
see prev comment 

you should not override code without checking

2021-07-06 13:51 UTC, tehilaR2 commented on SDKSamples/app/src/main/res/menu/menu_main.xml
> -<menu xmlns:android="http://schemas.android.com/apk/res/android"
why was it removed?

2021-07-07 16:04 UTC, tehilaR2 approved these changes

2021-07-07 16:04 UTC, merged