Bld 47285
bold360ai/bold360-mobile-samples-android pull request #39
Opened 2021-08-09 13:48 UTC by ozLogmein

2021-08-09 17:02 UTC, tehilaR2 reviewed
see my comment on the ticket

2021-08-09 17:04 UTC, tehilaR2 requested changes
see comment on the ticket

2021-08-12 10:34 UTC, tehilaR2 requested changes

2021-08-12 10:34 UTC, tehilaR2 commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/BoldUploadNoUI.kt
> +            if (code == -100 && !isFinishing) finish()
-100 is what??

2021-08-12 10:34 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/topicsbase/BasicChat.kt
> +            runMain{ toast(error.toString(), Toast.LENGTH_SHORT) } ?: finish()
did u make sure all samples should be finished when the chat can't be loaded?
what about samples that have multiple screens . why aren't u going back to the account fragment as done in the `onBackPressed`

2021-08-16 07:09 UTC, ozLogmein commented on SDKSamples/app/src/main/java/com/sdk/samples/topics/BoldUploadNoUI.kt
> +            if (code == -100 && !isFinishing) finish()
INPUT_OUTPUT_ERROR

2021-08-16 07:13 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/topicsbase/BasicChat.kt
> +            runMain{ toast(error.toString(), Toast.LENGTH_SHORT) } ?: finish()
ill call onBackPressed. it will be handled by the sample itself if it is being overridden.

2021-08-16 10:16 UTC, tehilaR2 approved these changes

2021-08-16 10:33 UTC, merged