[BLD-47253] - added continuity repository
bold360ai/bold360-mobile-samples-android pull request #40
Opened 2021-08-09 14:57 UTC by ozLogmein

2021-08-09 16:56 UTC, tehilaR2 requested changes

2021-08-09 16:56 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/JsonSampleRepository.kt
> +    fun saveVisitorToken( key: String, visitorToken: String? )
not sure about using the phrase "visitorToken".
today the id is of visitorToken - tomorrow it will be changed to visitorId, sessionNumber, etc... 
it should be more generic. 
maybe `sessionToken`

2021-08-09 16:56 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val updateVisitorToken: (account: BotAccount) -> Unit = { account ->
why the method declared as member that referencing a method.
This is a method and it's a val == can't be changed, so why are u using a member?

2021-08-09 16:56 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val getVisitorToken: (account: BotAccount) -> String? = { account ->
same as comment before - why not declaring it as a regular method?

2021-08-10 08:12 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val updateVisitorToken: (account: BotAccount) -> Unit = { account ->
I need to use the repository as a reference only.
can't do it via a method.

2021-08-10 08:12 UTC, ozLogmein commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val getVisitorToken: (account: BotAccount) -> String? = { account ->
I need to use the repository as a reference only.
can't do it via a method.

2021-08-12 10:30 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val updateVisitorToken: (account: BotAccount) -> Unit = { account ->
i don't see the relevance. 
currently updateVisitorToken points to a method which access the repository 
why can't it be a method which access the repository 

why is it a member - it's not an interface implementation, it's not changeable.

2021-08-12 10:30 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/chatComponents/customProviders/SimpleAccountProvider.kt
> +    val getVisitorToken: (account: BotAccount) -> String? = { account ->
same as previous...

2021-08-16 10:11 UTC, tehilaR2 requested changes

2021-08-16 10:11 UTC, tehilaR2 commented on SDKSamples/common/src/main/java/com/common/utils/chatForm/JsonSampleRepository.kt
> +    fun saveVisitorToken(key: String, sessionToken: String? )
wasn't that changed to sessionToken?

2021-08-16 16:51 UTC, tehilaR2 approved these changes

2021-08-16 16:58 UTC, merged